Repository Unity-Technologies/com.unity.netcode.gameobjects, pull requests merged in 2021-11, with the labels that each got.

#1379 fix: load event completed fires early
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Runtime/SceneManagement/NetworkSceneManager.cs
  testproject/Assets/Tests/Runtime/NetworkSceneManagerTests.cs
Labels: type:backport-release-1.0.0

#1400 fix: Change tools install link URL
  com.unity.netcode.gameobjects/Editor/NetworkManagerEditor.cs
Labels: type:backport-release-1.0.0

#1403 fix: Address packet overflow issues in the UTP adapter
  com.unity.netcode.adapter.utp/CHANGELOG.md
  com.unity.netcode.adapter.utp/Runtime/UnityTransport.cs
Labels: type:backport-release-1.0.0

#1354 fix: In-scene NetworkObjects disabled but never re-enabled after scene transition
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Runtime/SceneManagement/NetworkSceneManager.cs
  testproject/Assets/Tests/Runtime/NetworkSceneManagerTests.cs
Labels: type:backport-release-1.0.0

#1393 fix: RPC ILPP generating invalid IL code when using `this` instead of `this ref` for the FastBufferReader/FastBufferWriter parameter of an extension method.
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Editor/CodeGen/NetworkBehaviourILPP.cs
  testproject/Assets/Tests/Runtime/RpcUserSerializableTypesTest.cs
Labels: type:backport-release-1.0.0

#1398 refactor: remove misc defunct files
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Runtime/Collections.meta
  com.unity.netcode.gameobjects/Runtime/Collections/FixedQueue.cs
  com.unity.netcode.gameobjects/Runtime/Collections/FixedQueue.cs.meta
  com.unity.netcode.gameobjects/Runtime/Metrics/StreamExtensions.cs
  com.unity.netcode.gameobjects/Runtime/Metrics/StreamExtensions.cs.meta
  com.unity.netcode.gameobjects/Runtime/Reflection.meta
  com.unity.netcode.gameobjects/Runtime/Reflection/TypeExtensions.cs
  com.unity.netcode.gameobjects/Runtime/Reflection/TypeExtensions.cs.meta
Labels: type:backport-release-1.0.0

#1402 fix: Fixed a runtime error when passing an array of struct INetworkSerializables to an RPC
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Runtime/Serialization/FastBufferWriter.cs
  testproject/Assets/Tests/Runtime/RpcUserSerializableTypesTest.cs
Labels: type:backport-release-1.0.0

#1409 fix: using the proper NetworkManagers for the two clients in TimeMultiInstanceTest
  com.unity.netcode.gameobjects/Tests/Runtime/Timing/TimeMultiInstanceTest.cs
Labels: stat:ready-to-merge, type:backport-release-1.0.0

#1221 fix: run disconnect callback before internal disconnect logic
  com.unity.netcode.gameobjects/Runtime/Core/NetworkManager.cs
Labels: stat:ready-to-merge, type:backport-release-1.0.0

#1383 fix: Fix NetworkVariable<INetworkSerializable> so that it will properly call NetworkSerialize instead of using the default memcpy operation.
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Editor/CodeGen/CodeGenHelpers.cs
  com.unity.netcode.gameobjects/Editor/CodeGen/INetworkSerializableILPP.cs
  com.unity.netcode.gameobjects/Editor/CodeGen/INetworkSerializableILPP.cs.meta
  com.unity.netcode.gameobjects/Editor/CodeGen/RuntimeAccessModifiersILPP.cs
  com.unity.netcode.gameobjects/Runtime/NetworkVariable/NetworkVariable.cs
  com.unity.netcode.gameobjects/Runtime/NetworkVariable/NetworkVariableHelper.cs
  com.unity.netcode.gameobjects/Runtime/NetworkVariable/NetworkVariableHelper.cs.meta
  com.unity.netcode.gameobjects/Tests/Runtime/MultiInstanceHelpers.cs
  com.unity.netcode.gameobjects/Tests/Runtime/NetworkVariableTests.cs
Labels: stat:ready-to-merge, type:backport-release-1.0.0

#1385 fix: remove the buffer size limit when computing a hash in NetworkConfig
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Runtime/Configuration/NetworkConfig.cs
Labels: stat:ready-to-merge, type:backport-release-1.0.0

#1323 fix: Fixed a few memory leak cases when shutting down NetworkManager during Incoming Message Queue processing
  com.unity.netcode.gameobjects/Runtime/Core/NetworkManager.cs
  com.unity.netcode.gameobjects/Runtime/Core/SnapshotSystem.cs
  com.unity.netcode.gameobjects/Runtime/Messaging/MessagingSystem.cs
  com.unity.netcode.gameobjects/Runtime/Spawning/NetworkSpawnManager.cs
  com.unity.netcode.gameobjects/Tests/Editor/StartStopTests.cs
  testproject/Assets/Tests/Runtime/NoMemoryLeakOnNetworkManagerShutdownTest.cs
  testproject/Assets/Tests/Runtime/NoMemoryLeakOnNetworkManagerShutdownTest.cs.meta
  testproject/Assets/Tests/Runtime/Support/ShutdownDuringOnNetworkSpawnBehaviour.cs
  testproject/Assets/Tests/Runtime/Support/ShutdownDuringOnNetworkSpawnBehaviour.cs.meta
  testproject/Assets/Tests/Runtime/Support/SpawnRpcDespawn.cs
Labels: type:backport-release-1.0.0

#1390 fix: OnNetworkDespawn not called during shutdown
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Components/NetworkRigidbody2D.cs
  com.unity.netcode.gameobjects/Components/NetworkTransform.cs
  com.unity.netcode.gameobjects/Runtime/Core/NetworkBehaviour.cs
  com.unity.netcode.gameobjects/Runtime/Core/NetworkManager.cs
  com.unity.netcode.gameobjects/Runtime/Spawning/NetworkSpawnManager.cs
  com.unity.netcode.gameobjects/Tests/Runtime/NetworkObject/NetworkObjectOnNetworkDespawnTests.cs
  com.unity.netcode.gameobjects/Tests/Runtime/NetworkObject/NetworkObjectOnNetworkDespawnTests.cs.meta
  com.unity.netcode.gameobjects/Tests/Runtime/Physics/NetworkRigidbody2DTest.cs
Labels: type:backport-release-1.0.0

#1384 fix: increases maximum message size to int.MaxValue
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Runtime/Configuration/NetworkConstants.cs
  com.unity.netcode.gameobjects/Runtime/Core/NetworkBehaviour.cs
  com.unity.netcode.gameobjects/Runtime/Messaging/CustomMessageManager.cs
  com.unity.netcode.gameobjects/Runtime/Messaging/MessageHeader.cs
  com.unity.netcode.gameobjects/Runtime/Messaging/Messages/NamedMessage.cs
  com.unity.netcode.gameobjects/Runtime/Messaging/Messages/UnnamedMessage.cs
  com.unity.netcode.gameobjects/Runtime/Messaging/MessagingSystem.cs
  com.unity.netcode.gameobjects/Runtime/Messaging/NetworkContext.cs
  com.unity.netcode.gameobjects/Runtime/Spawning/NetworkSpawnManager.cs
  com.unity.netcode.gameobjects/Tests/Editor/Messaging/MessageReceivingTests.cs
  com.unity.netcode.gameobjects/Tests/Editor/Messaging/MessageSendingTests.cs
  com.unity.netcode.gameobjects/Tests/Runtime/Metrics/MessagingMetricsTests.cs
  com.unity.netcode.gameobjects/Tests/Runtime/Metrics/OwnershipChangeMetricsTests.cs
  com.unity.netcode.gameobjects/Tests/Runtime/Metrics/ServerLogsMetricTests.cs
  com.unity.netcode.gameobjects/Tests/Runtime/Metrics/TransportBytesMetricsTests.cs
Labels: type:backport-release-1.0.0, type:backport-release-1.1.0

#1425 fix: Set shutdown flags back to false once shutdown is complete
  com.unity.netcode.gameobjects/Runtime/Core/NetworkManager.cs
  com.unity.netcode.gameobjects/Tests/Runtime/StopStartRuntimeTests.cs
  com.unity.netcode.gameobjects/Tests/Runtime/StopStartRuntimeTests.cs.meta
  com.unity.netcode.gameobjects/Tests/Runtime/Transport/SIPTransport.cs
Labels: type:backport-release-1.0.0, type:backport-release-1.1.0

#1415 fix: Address packet overflow issues in the UTP adapter (1.1.0)
  com.unity.netcode.adapter.utp/CHANGELOG.md
  com.unity.netcode.adapter.utp/Runtime/UnityTransport.cs
Labels: stat:ready-to-merge

#1412 fix: using the proper NetworkManagers for the two clients (#1409)
  com.unity.netcode.gameobjects/Tests/Runtime/Timing/TimeMultiInstanceTest.cs
Labels: stat:ready-to-merge

#1414 fix: using the proper NetworkManagers for the two clients (#1409)
  com.unity.netcode.gameobjects/Tests/Runtime/Timing/TimeMultiInstanceTest.cs
Labels: stat:ready-to-merge

#1433 fix: NetworkManager destroys client player object with DontDestroyWithOwner set
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Runtime/Core/NetworkManager.cs
  com.unity.netcode.gameobjects/Tests/Runtime/NetworkObject/NetworkObjectDestroyTests.cs
Labels: type:backport-release-1.1.0

#1441 fix: Prevent an exception in UTP when host disconnects
  com.unity.netcode.adapter.utp/CHANGELOG.md
  com.unity.netcode.adapter.utp/Runtime/UnityTransport.cs
Labels: type:backport-release-1.0.0, type:backport-release-1.1.0

#1434 fix: (external) avoid NullReferenceException on ImportReferences call
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Editor/CodeGen/NetworkBehaviourILPP.cs
Labels: type:backport-release-1.0.0

#1451 chore: Updating collections and UTP
  com.unity.netcode.adapter.utp/CHANGELOG.md
  com.unity.netcode.adapter.utp/Runtime/UnityTransport.cs
  com.unity.netcode.adapter.utp/Tests/Runtime/Helpers/DriverClient.cs
  com.unity.netcode.adapter.utp/package.json
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/package.json
Labels: type:backport-release-1.0.0

#1464 fix: load event completed fires early (#1379)
  com.unity.netcode.gameobjects/Runtime/SceneManagement/NetworkSceneManager.cs
  testproject/Assets/Tests/Runtime/NetworkSceneManagerTests.cs
Labels: stat:ready-to-merge

#1461 fix: remove the buffer size limit when computing a hash in NetworkCon…
  com.unity.netcode.gameobjects/Runtime/Configuration/NetworkConfig.cs
Labels: stat:ready-to-merge

#1457 fix: Change tools install link URL (#1400)
  com.unity.netcode.gameobjects/Editor/NetworkManagerEditor.cs
Labels: stat:ready-to-merge

#1467 fix: run disconnect callback before internal disconnect logic (#1221)
  com.unity.netcode.gameobjects/Runtime/Core/NetworkManager.cs
Labels: stat:ready-to-merge

#1456 fix: Fixed a runtime error when passing an array of struct INetworkSe…
  com.unity.netcode.gameobjects/Runtime/Serialization/FastBufferWriter.cs
  testproject/Assets/Tests/Runtime/RpcUserSerializableTypesTest.cs
Labels: stat:ready-to-merge

#1459 fix: RPC ILPP generating invalid IL code when using `this` instead of…
  com.unity.netcode.gameobjects/Editor/CodeGen/NetworkBehaviourILPP.cs
  testproject/Assets/Tests/Runtime/RpcUserSerializableTypesTest.cs
Labels: stat:ready-to-merge

#1465 fix: In-scene NetworkObjects disabled but never re-enabled after scen…
  com.unity.netcode.gameobjects/Runtime/SceneManagement/NetworkSceneManager.cs
  testproject/Assets/Tests/Runtime/NetworkSceneManagerTests.cs
Labels: stat:ready-to-merge

#1458 refactor: remove misc defunct files (#1398)
  com.unity.netcode.gameobjects/Runtime/Collections.meta
  com.unity.netcode.gameobjects/Runtime/Collections/FixedQueue.cs
  com.unity.netcode.gameobjects/Runtime/Collections/FixedQueue.cs.meta
  com.unity.netcode.gameobjects/Runtime/Metrics/StreamExtensions.cs
  com.unity.netcode.gameobjects/Runtime/Metrics/StreamExtensions.cs.meta
  com.unity.netcode.gameobjects/Runtime/Reflection.meta
  com.unity.netcode.gameobjects/Runtime/Reflection/TypeExtensions.cs
  com.unity.netcode.gameobjects/Runtime/Reflection/TypeExtensions.cs.meta
Labels: stat:ready-to-merge

#1466 fix: Fixed a few memory leak cases when shutting down NetworkManager …
  com.unity.netcode.gameobjects/Runtime/Core/NetworkManager.cs
  com.unity.netcode.gameobjects/Runtime/Core/SnapshotSystem.cs
  com.unity.netcode.gameobjects/Runtime/Messaging/MessagingSystem.cs
  com.unity.netcode.gameobjects/Runtime/Spawning/NetworkSpawnManager.cs
  com.unity.netcode.gameobjects/Tests/Editor/StartStopTests.cs
  testproject/Assets/Tests/Runtime/NoMemoryLeakOnNetworkManagerShutdownTest.cs
  testproject/Assets/Tests/Runtime/NoMemoryLeakOnNetworkManagerShutdownTest.cs.meta
  testproject/Assets/Tests/Runtime/Support/ShutdownDuringOnNetworkSpawnBehaviour.cs
  testproject/Assets/Tests/Runtime/Support/ShutdownDuringOnNetworkSpawnBehaviour.cs.meta
  testproject/Assets/Tests/Runtime/Support/SpawnRpcDespawn.cs
Labels: stat:ready-to-merge

#1455 fix: Set shutdown flags back to false once shutdown is complete (#1425)
  com.unity.netcode.gameobjects/Runtime/Core/NetworkManager.cs
  com.unity.netcode.gameobjects/Tests/Runtime/StopStartRuntimeTests.cs
  com.unity.netcode.gameobjects/Tests/Runtime/StopStartRuntimeTests.cs.meta
  com.unity.netcode.gameobjects/Tests/Runtime/Transport/SIPTransport.cs
Labels: stat:ready-to-merge

#1460 fix: OnNetworkDespawn not called during shutdown (#1390)
  com.unity.netcode.gameobjects/Components/NetworkRigidbody2D.cs
  com.unity.netcode.gameobjects/Components/NetworkTransform.cs
  com.unity.netcode.gameobjects/Runtime/Core/NetworkBehaviour.cs
  com.unity.netcode.gameobjects/Runtime/Core/NetworkManager.cs
  com.unity.netcode.gameobjects/Runtime/Spawning/NetworkSpawnManager.cs
  com.unity.netcode.gameobjects/Tests/Runtime/NetworkObject/NetworkObjectOnNetworkDespawnTests.cs
  com.unity.netcode.gameobjects/Tests/Runtime/NetworkObject/NetworkObjectOnNetworkDespawnTests.cs.meta
  com.unity.netcode.gameobjects/Tests/Runtime/Physics/NetworkRigidbody2DTest.cs
Labels: stat:ready-to-merge

#1462 fix: increases maximum message size to int.MaxValue (#1384)
  com.unity.netcode.gameobjects/Runtime/Configuration/NetworkConstants.cs
  com.unity.netcode.gameobjects/Runtime/Core/NetworkBehaviour.cs
  com.unity.netcode.gameobjects/Runtime/Messaging/CustomMessageManager.cs
  com.unity.netcode.gameobjects/Runtime/Messaging/MessageHeader.cs
  com.unity.netcode.gameobjects/Runtime/Messaging/Messages/NamedMessage.cs
  com.unity.netcode.gameobjects/Runtime/Messaging/Messages/UnnamedMessage.cs
  com.unity.netcode.gameobjects/Runtime/Messaging/MessagingSystem.cs
  com.unity.netcode.gameobjects/Runtime/Messaging/NetworkContext.cs
  com.unity.netcode.gameobjects/Runtime/Spawning/NetworkSpawnManager.cs
  com.unity.netcode.gameobjects/Tests/Editor/Messaging/MessageReceivingTests.cs
  com.unity.netcode.gameobjects/Tests/Editor/Messaging/MessageSendingTests.cs
  com.unity.netcode.gameobjects/Tests/Runtime/Metrics/MessagingMetricsTests.cs
  com.unity.netcode.gameobjects/Tests/Runtime/Metrics/OwnershipChangeMetricsTests.cs
  com.unity.netcode.gameobjects/Tests/Runtime/Metrics/ServerLogsMetricTests.cs
  com.unity.netcode.gameobjects/Tests/Runtime/Metrics/TransportBytesMetricsTests.cs
Labels: stat:ready-to-merge

#1477 fix: make sure we translate transportId to clientId
  com.unity.netcode.gameobjects/Runtime/Core/NetworkManager.cs
Labels: type:backport-release-1.0.0

#1478 fix: Updating UTP to fix Analyzers compile issue in 20.3
  com.unity.netcode.adapter.utp/CHANGELOG.md
  com.unity.netcode.adapter.utp/package.json
Labels: type:backport-release-1.0.0
