Repository Unity-Technologies/com.unity.netcode.gameobjects, pull requests merged in 2021-12, with the labels that each got.

#1405 feat: networkscenemanager scenemanager interface override
  com.unity.netcode.adapter.utp/Tests/Runtime/ConnectionTests.cs
  com.unity.netcode.adapter.utp/Tests/Runtime/TransportTests.cs
  com.unity.netcode.gameobjects/Runtime/SceneManagement/ISceneManagerHandler.cs
  com.unity.netcode.gameobjects/Runtime/SceneManagement/ISceneManagerHandler.cs.meta
  com.unity.netcode.gameobjects/Runtime/SceneManagement/NetworkSceneManager.cs
  com.unity.netcode.gameobjects/Runtime/SceneManagement/SceneEventData.cs
  com.unity.netcode.gameobjects/Tests/Runtime/BaseMultiInstanceTest.cs
  com.unity.netcode.gameobjects/Tests/Runtime/IntegrationTestSceneHandler.cs
  com.unity.netcode.gameobjects/Tests/Runtime/IntegrationTestSceneHandler.cs.meta
  com.unity.netcode.gameobjects/Tests/Runtime/MultiInstanceHelpers.cs
  com.unity.netcode.gameobjects/Tests/Runtime/Timing/TimeInitializationTest.cs
  testproject-tools-integration/Assets/Tests/Runtime/SceneEventTests.cs
  testproject/Assets/Tests/Manual/Scripts/NetworkPrefabPoolAdditive.cs
  testproject/Assets/Tests/Runtime/DontDestroyOnLoadTests.cs
  testproject/Assets/Tests/Runtime/NetworkSceneManagerTests.cs
  testproject/Assets/Tests/Runtime/ObjectParenting/NetworkObjectParentingTests.cs
Labels: type:backport-release-1.1.0

#1500 fix: remove ownership key not found exception
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Runtime/Spawning/NetworkSpawnManager.cs
  com.unity.netcode.gameobjects/Tests/Runtime/NetworkObject/NetworkObjectOwnershipTests.cs
Labels: type:backport-release-1.0.0

#1505 fix: network transform pooled objects reset
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Components/NetworkTransform.cs
  com.unity.netcode.gameobjects/Tests/Runtime/NetworkTransform/NetworkTransformTests.cs
Labels: type:backport-release-1.0.0

#1518 fix: disable respawned position test
  com.unity.netcode.gameobjects/Tests/Runtime/NetworkTransform/NetworkTransformTests.cs
Labels: type:backport-release-1.0.0

#1511 fix: host NetworkManager.LocalClient not being set
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Runtime/Core/NetworkManager.cs
  testproject/Assets/Tests/Runtime/NetworkManagerTests.cs
  testproject/Assets/Tests/Runtime/NetworkManagerTests.cs.meta
Labels: type:backport-release-1.0.0

#1479 fix: Don't throw when shutting down a config-less manager
  com.unity.netcode.gameobjects/Runtime/Core/NetworkManager.cs
  com.unity.netcode.gameobjects/Tests/Editor/StartStopTests.cs
Labels: stat:ready-to-merge, type:backport-release-1.0.0

#1501 chore: updating UTP to pre.10
  com.unity.netcode.adapter.utp/CHANGELOG.md
  com.unity.netcode.adapter.utp/package.json
Labels: stat:ready-to-merge, type:backport-release-1.0.0

#1512 feat: Enable fragmentation for unreliable delivery (UTP)
  com.unity.netcode.adapter.utp/CHANGELOG.md
  com.unity.netcode.adapter.utp/Runtime/UnityTransport.cs
  com.unity.netcode.adapter.utp/Tests/Runtime/TransportTests.cs
Labels: stat:ready-to-merge, type:backport-release-1.0.0

#1484 fix: NetworkManager always sent to the DDOL and cannot be nested
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Editor/NetworkManagerEditor.cs
  com.unity.netcode.gameobjects/Editor/NetworkManagerHelper.cs
  com.unity.netcode.gameobjects/Editor/NetworkManagerHelper.cs.meta
  com.unity.netcode.gameobjects/Runtime/Core/NetworkManager.cs
  com.unity.netcode.gameobjects/Runtime/SceneManagement/NetworkSceneManager.cs
  com.unity.netcode.gameobjects/Tests/Editor/NetworkManagerConfigurationTests.cs
  com.unity.netcode.gameobjects/Tests/Editor/NetworkManagerConfigurationTests.cs.meta
  com.unity.netcode.gameobjects/Tests/Runtime/NetworkTransform/NetworkTransformTests.cs
  testproject/Assets/Tests/Runtime/DontDestroyOnLoadTests.cs
  testproject/Assets/Tests/Runtime/NestedNetworkManagerTests.cs
  testproject/Assets/Tests/Runtime/NestedNetworkManagerTests.cs.meta
  testproject/Assets/Tests/Runtime/SmokeTest/SceneReferenceValidationState.cs
Labels: type:backport-release-1.0.0

#1513 fix: NetworkConfig checksum hash include TickRate
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Runtime/Configuration/NetworkConfig.cs
Labels: stat:ready-to-merge

#1531 fix: make sure we translate transportId to clientId
  com.unity.netcode.gameobjects/Runtime/Core/NetworkManager.cs
Labels: stat:ready-to-merge

#1504 fix: Don't throw when shutting down a config-less manager
  com.unity.netcode.gameobjects/Runtime/Core/NetworkManager.cs
  com.unity.netcode.gameobjects/Tests/Editor/StartStopTests.cs
Labels: stat:ready-to-merge

#1532 fix: remove ownership key not found exception
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Runtime/Spawning/NetworkSpawnManager.cs
  com.unity.netcode.gameobjects/Tests/Runtime/NetworkObject/NetworkObjectOwnershipTests.cs
Labels: stat:ready-to-merge

#1533 fix: network transform pooled objects reset
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Components/NetworkTransform.cs
  com.unity.netcode.gameobjects/Tests/Runtime/NetworkTransform/NetworkTransformTests.cs
Labels: stat:ready-to-merge

#1536 fix: host NetworkManager.LocalClient not being set
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Runtime/Core/NetworkManager.cs
  testproject/Assets/Tests/Runtime/NetworkManagerTests.cs
  testproject/Assets/Tests/Runtime/NetworkManagerTests.cs.meta
Labels: stat:ready-to-merge
