Repository Unity-Technologies/com.unity.netcode.gameobjects, pull requests merged in 2022-02, with the labels that each got.

#1640 fix: Correctly dispose of everything in adapter's OnDestroy
  com.unity.netcode.adapter.utp/CHANGELOG.md
  com.unity.netcode.adapter.utp/Runtime/UnityTransport.cs
Labels: type:backport-release-1.0.0

#1634 chore: update Tools asmdef references
  com.unity.netcode.gameobjects/Runtime/com.unity.netcode.runtime.asmdef
Labels: type:backport-release-1.0.0

#1654 fix: mtt-1393
  com.unity.netcode.gameobjects/Components/Interpolator/BufferedLinearInterpolator.cs
  com.unity.netcode.gameobjects/Components/NetworkTransform.cs
Labels: type:backport-release-1.0.0

#1648 fix: Don't keep bad packets in the adapter's send queues
  com.unity.netcode.adapter.utp/CHANGELOG.md
  com.unity.netcode.adapter.utp/Runtime/UnityTransport.cs
Labels: type:backport-release-1.0.0

#1651 fix: add new tool assembly names that were missing - release 1.0.0 backport
  com.unity.netcode.gameobjects/Tests/Editor/com.unity.netcode.editortests.asmdef
  com.unity.netcode.gameobjects/Tests/Runtime/com.unity.netcode.runtimetests.asmdef
  testproject-tools-integration/Assets/Tests/Runtime/testproject.toolsintegration.runtimetests.asmdef
Labels: priority:high

#1676 fix: Add new tool assembly names that were missing - develop
  com.unity.netcode.gameobjects/Tests/Editor/com.unity.netcode.editortests.asmdef
  com.unity.netcode.gameobjects/Tests/Runtime/com.unity.netcode.runtimetests.asmdef
  testproject-tools-integration/Assets/Tests/Runtime/testproject.toolsintegration.runtimetests.asmdef
Labels: priority:high, stat:backported-release-1.0.0

#1649 fix: Clear adapter send queues on client disconnection
  com.unity.netcode.adapter.utp/CHANGELOG.md
  com.unity.netcode.adapter.utp/Tests/Runtime/ConnectionTests.cs
Labels: stat:backported-release-1.0.0

#1678 fix: unet removed from unity trunk
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Runtime/Transports/UNET/UNetChannel.cs
  com.unity.netcode.gameobjects/Runtime/Transports/UNET/UNetTransport.cs
  com.unity.netcode.gameobjects/Runtime/com.unity.netcode.runtime.asmdef
  com.unity.netcode.gameobjects/Tests/Runtime/Helpers/NetworkManagerHelper.cs
  com.unity.netcode.gameobjects/Tests/Runtime/com.unity.netcode.runtimetests.asmdef
  testproject/Assets/Scripts/CommandLineHandler.cs
  testproject/Assets/Scripts/testproject.asmdef
  testproject/Assets/Tests/Runtime/testproject.runtimetests.asmdef
Labels: type:backport-release-1.0.0

#1691 feat: networkscenemanager interface override (backport)
  com.unity.netcode.gameobjects/Runtime/SceneManagement/ISceneManagerHandler.cs
  com.unity.netcode.gameobjects/Runtime/SceneManagement/ISceneManagerHandler.cs.meta
  com.unity.netcode.gameobjects/Runtime/SceneManagement/NetworkSceneManager.cs
  com.unity.netcode.gameobjects/Runtime/SceneManagement/SceneEventData.cs
  com.unity.netcode.gameobjects/Tests/Runtime/BaseMultiInstanceTest.cs
  com.unity.netcode.gameobjects/Tests/Runtime/IntegrationTestSceneHandler.cs
  com.unity.netcode.gameobjects/Tests/Runtime/IntegrationTestSceneHandler.cs.meta
  com.unity.netcode.gameobjects/Tests/Runtime/MultiInstanceHelpers.cs
  com.unity.netcode.gameobjects/Tests/Runtime/Timing/TimeInitializationTest.cs
  testproject-tools-integration/Assets/Tests/Runtime/SceneEventTests.cs
  testproject/Assets/Tests/Runtime/DontDestroyOnLoadTests.cs
  testproject/Assets/Tests/Runtime/NetworkSceneManagerTests.cs
  testproject/Assets/Tests/Runtime/ObjectParenting/NetworkObjectParentingTests.cs
Labels: type:backport-release-1.0.0

#1711 test: replacing testrails manual tests with automated tests (backport)
  com.unity.netcode.gameobjects/Tests/Runtime/RpcManyClientsTests.cs
  com.unity.netcode.gameobjects/Tests/Runtime/RpcManyClientsTests.cs.meta
Labels: stat:ready-to-merge

#1696 chore: Update UTP dependency to 1.0.0-pre.13
  com.unity.netcode.adapter.utp/CHANGELOG.md
  com.unity.netcode.adapter.utp/package.json
Labels: stat:ready-to-merge

#1718 chore: update branches lists in workflow configs
  .github/workflows/autoupdate.yaml
  .github/workflows/conventional-pr.yml
Labels: stat:ready-to-merge

#1719 chore: fix minor typo in exception message
  com.unity.netcode.gameobjects/Runtime/Core/NetworkManager.cs
Labels: stat:ready-to-merge

#1681 fix: Disallowed async keyword in RPCs
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Editor/CodeGen/NetworkBehaviourILPP.cs
Labels: stat:ready-to-merge

#1686 fix: cast messagesize as uint (credit: kaen / #1592)
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Runtime/Messaging/MessagingSystem.cs
  com.unity.netcode.gameobjects/Tests/Runtime/NetworkObject/NetworkObjectSpawnManyObjectsTests.cs
  com.unity.netcode.gameobjects/Tests/Runtime/NetworkObject/NetworkObjectSpawnManyObjectsTests.cs.meta
Labels: stat:ready-to-merge

#1720 fix: error when serializing ConnectionApprovalMessage with scene management disabled when one or more objects is hidden via the CheckObjectVisibility delegate (backport)
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Runtime/Core/NetworkManager.cs
  com.unity.netcode.gameobjects/Runtime/Messaging/Messages/ConnectionApprovedMessage.cs
  com.unity.netcode.gameobjects/Tests/Runtime/Components/NetworkVisibilityComponent.cs
  com.unity.netcode.gameobjects/Tests/Runtime/Components/NetworkVisibilityComponent.cs.meta
  com.unity.netcode.gameobjects/Tests/Runtime/MultiInstanceHelpers.cs
  com.unity.netcode.gameobjects/Tests/Runtime/NetworkVisibilityTests.cs
  com.unity.netcode.gameobjects/Tests/Runtime/NetworkVisibilityTests.cs.meta
Labels: stat:ready-to-merge

#1680 fix: Fixed CheckObjectVisibility delegate not being properly invoked for connecting clients when Scene Management is enabled.
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Runtime/SceneManagement/SceneEventData.cs
  com.unity.netcode.gameobjects/Runtime/Spawning/NetworkSpawnManager.cs
  com.unity.netcode.gameobjects/Tests/Runtime/NetworkVisibilityTests.cs
Labels: stat:ready-to-merge

#1682 fix: NetworkList to call INetworkSerializable's NetworkSerialize() method properly
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Runtime/NetworkVariable/Collections/NetworkList.cs
  com.unity.netcode.gameobjects/Runtime/NetworkVariable/NetworkVariable.cs
  com.unity.netcode.gameobjects/Tests/Runtime/NetworkVariableTests.cs
Labels: stat:ready-to-merge

#1723 feat: add WaitForMessageOfType to MultiInstanceHelpers (backport)
  com.unity.netcode.gameobjects/Tests/Runtime/MultiInstanceHelpers.cs
  com.unity.netcode.gameobjects/Tests/Runtime/RpcTests.cs
Labels: stat:ready-to-merge

#1724 fix: Creating a zero-length FastBufferReader no longer reports its size as 1 (backport)
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Runtime/Core/NetworkBehaviour.cs
  com.unity.netcode.gameobjects/Runtime/Serialization/FastBufferReader.cs
  com.unity.netcode.gameobjects/Tests/Editor/Serialization/FastBufferReaderTests.cs
Labels: stat:ready-to-merge

#1736 chore: update `CODEOWNERS`
  .github/CODEOWNERS
Labels: stat:ready-to-merge
