Repository Unity-Technologies/com.unity.netcode.gameobjects, pull requests merged in 2022-01, with the labels that each got.

#1565 chore: update sdk package dependencies
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/package.json
Labels: type:backport-release-1.0.0

#1562 chore: Increment package versions for NGO 1.0.0-pre.4 and update changelogs
  com.unity.netcode.adapter.utp/CHANGELOG.md
  com.unity.netcode.adapter.utp/package.json
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/package.json
Labels: stat:backported-release-1.0.0

#1584 fix: Rename 'Send Queue Batch Size' field in adapter
  com.unity.netcode.adapter.utp/CHANGELOG.md
  com.unity.netcode.adapter.utp/Runtime/UnityTransport.cs
  com.unity.netcode.adapter.utp/Tests/Runtime/Helpers/DriverClient.cs
  com.unity.netcode.adapter.utp/Tests/Runtime/TransportTests.cs
Labels: type:backport-release-1.0.0

#1603 docs: Update UTP doc package link to doc site
  com.unity.netcode.adapter.utp/Documentation~/Manual.md
  com.unity.netcode.adapter.utp/README.md
Labels: type:backport-release-1.0.0

#1596 fix: Lift ~44KB limit for reliable payloads in the adapter
  com.unity.netcode.adapter.utp/CHANGELOG.md
  com.unity.netcode.adapter.utp/Runtime/BatchedReceiveQueue.cs
  com.unity.netcode.adapter.utp/Runtime/BatchedSendQueue.cs
  com.unity.netcode.adapter.utp/Runtime/UnityTransport.cs
  com.unity.netcode.adapter.utp/Tests/Editor/BatchedReceiveQueueTests.cs
  com.unity.netcode.adapter.utp/Tests/Editor/BatchedSendQueueTests.cs
  com.unity.netcode.adapter.utp/Tests/Runtime/ConnectionTests.cs
  com.unity.netcode.adapter.utp/Tests/Runtime/Helpers/RuntimeTestsHelpers.cs
  com.unity.netcode.adapter.utp/Tests/Runtime/TransportTests.cs
Labels: stat:backported-release-1.0.0

#1609 feat: Simpler relay data setters in the adapter
  com.unity.netcode.adapter.utp/CHANGELOG.md
  com.unity.netcode.adapter.utp/Runtime/UnityTransport.cs
Labels: type:backport-release-1.0.0

#1614 fix: rounding issue with tick calculation
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Runtime/Timing/NetworkTime.cs
  com.unity.netcode.gameobjects/Tests/Editor/Timing/NetworkTimeTests.cs
Labels: type:backport-release-1.0.0

#1606 fix: refresh cancommit value of ClientNetworkTransform
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Samples/ClientNetworkTransform/Scripts/ClientNetworkTransform.cs
Labels: type:backport-release-1.0.0

#1615 chore: Update UTP adapter dependencies
  com.unity.netcode.adapter.utp/CHANGELOG.md
  com.unity.netcode.adapter.utp/package.json
Labels: type:backport-release-1.0.0

#1618 fix: refresh cancommit value of ClientNetworkTransform - release 1.0.0 backport
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Samples/ClientNetworkTransform/Scripts/ClientNetworkTransform.cs
Labels: stat:ready-to-merge

#1605 feat: Allow specifying a different listen address in the adapter
  com.unity.netcode.adapter.utp/CHANGELOG.md
  com.unity.netcode.adapter.utp/Runtime/UnityTransport.cs
  com.unity.netcode.adapter.utp/Tests/Runtime/ConnectionTests.cs
Labels: type:backport-release-1.0.0

#1621 chore: network list contains missing changelog
  com.unity.netcode.adapter.utp/CHANGELOG.md
Labels: type:backport-release-1.0.0

#1626 chore: Increment package versions for NGO 1.0.0-pre.5 and update changelogs
  com.unity.netcode.adapter.utp/CHANGELOG.md
  com.unity.netcode.adapter.utp/package.json
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/package.json
Labels: stat:backported-release-1.0.0

#1631 fix: NetworkBehaviour spam generated when LogLevel is set to developer
  com.unity.netcode.gameobjects/CHANGELOG.md
  com.unity.netcode.gameobjects/Runtime/Core/NetworkBehaviour.cs
  com.unity.netcode.gameobjects/Tests/Runtime/NetworkBehaviourGenericTests.cs
  com.unity.netcode.gameobjects/Tests/Runtime/NetworkBehaviourGenericTests.cs.meta
Labels: type:backport-release-1.0.0

#1636 fix: Endpoint creation fails with empty listen address
  com.unity.netcode.adapter.utp/CHANGELOG.md
  com.unity.netcode.adapter.utp/Runtime/UnityTransport.cs
Labels: type:backport-release-1.0.0
